dataset: "fastMRI"

path_dataset: "${WORK}/diffuse/data/fastMRI/singlecoil_train"

# Model paths
model_dir: "/lustre/fswork/projects/rech/hlp/uha64uw/diffuse/data/fastMRI/models/"
model_name: "ann_1296.npz"

training:
    n_epochs: 4000
    batch_size: 64
    num_workers: 0
    lr: 2.0e-4

inference:
    n_t: 50  # Number of time steps
    n_samples: 15  # Number of samples for denoiser
    n_samples_cntrst: 16  # Number of contrastive samples
    n_loop_opt: 3  # Number of optimization loops
    lr: 0.1
    
sde:
    beta_min: 0.02
    beta_max: 5.0
    t0: 0.0
    tf: 2.0

unet:
    embedding_dim: 64
    upsampling: "pixel_shuffle"
    dt_embedding: 0.03125  # Time embedding step (tf/64)
    

mask:
    mask_type: "radial"  # or "spiral"
    num_lines: 5

task: "quality"