dataset: "WMH"
score_model: "UNet"
path_dataset: "${WORK}/diffuse/data/WMH"

# Model paths
model_dir: "/lustre/fsn1/projects/rech/hlp/uha64uw//diffuse/data/WMH/models_with_val_2000/"

training:
    n_epochs: 2000
    train_ratio: 0.8
    batch_size: 32
    nt_samples: 32 # Number of t samples for the score matching loss
    loss_weight: "weight_fun" 
    num_workers: 0
    lr: 2.0e-4

inference:
    n_t: 50  # Number of time steps
    n_samples: 150  # Number of samples for denoiser
    n_samples_cntrst: 151  # Number of contrastive samples
    n_loop_opt: 3  # Number of optimization loops
    lr: 0.1
    
sde:
    beta_min: 0.02
    beta_max: 5.0
    t0: 0.0
    tf: 2.0

unet:
    embedding_dim: 128
    upsampling: "pixel_shuffle"
    dim_mults: [1, 2, 4, 8]
    dt_embedding: 0.002  # Time embedding step (tf/2000)

mask:
    mask_type: "radial"  # or "spiral"
    num_lines: 5

task: "anomaly"