dataset: "fastMRI"
score_model: "UNet"
path_dataset: "${WORK}/diffuse/data/fastMRI"

# Model paths
model_dir: "/lustre/fsn1/projects/rech/hlp/uha64uw/diffuse/data/fastMRI/models_with_val_deepseek/"

training:
    n_epochs: 4000
    train_ratio: 0.8
    batch_size: 32
    nt_samples: 32
    loss: "noise_matching"
    num_workers: 0
    lr: 2.0e-4

inference:
    n_t: 25  # Number of time steps
    n_samples: 40  # Number of samples for denoiser
    n_samples_cntrst: 40  # Number of contrastive samples
    n_loop_opt: 2 # Number of optimization loops
    lr: 0.1

sde:
    beta_min: 0.02
    beta_max: 5.0
    t0: 0.0
    tf: 2.0

unet:
    embedding_dim: 64
    upsampling: "pixel_shuffle"
    dim_mults: [1, 2, 4, 8]
    dt_embedding: 0.002  # Time embedding step (tf/2000)

mask:
    mask_type: "radial"  # or "spiral"
    num_lines: 5

task: "quality"