path_dataset: "/lustre/fswork/projects/rech/hlp/uha64uw/sharingan/data/BRATS/ASNR-MICCAI-BraTS2023-Local-Synthesis-Challenge-Training"
save_path: "/lustre/fswork/projects/rech/hlp/uha64uw/sharingan/data/BRATS/models/"

dataset: "brats"

n_epochs: 4000
begin_epoch: 326
batch_size: 64
num_workers: 0

n_t: 64
tf: 2.0
lr: 2.0e-4