modality: "FLAIR"
slice_size_template: 49
begin_slice: 26

flair_template_path: "/lustre/fswork/projects/rech/hlp/uha64uw/projet_p/WMH/MNI-FLAIR-2.0mm.nii.gz"
path_dataset: "/lustre/fswork/projects/rech/hlp/uha64uw/projet_p/WMH"
save_path: "/lustre/fswork/projects/rech/hlp/uha64uw/projet_p/WMH/models/"

dataset: "wmh"

n_epochs: 4000
batch_size: 32
num_workers: 0

n_t: 300
tf: 2.0
lr: 2.0e-4